#!/usr/bin/env bash

export BASEPATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $BASEPATH/src/helper.sh
source $BASEPATH/config/config.sh

detect_platform

SUBCOMMAND=$1
shift 1

if [ "$SUBCOMMAND" == "install" ]; then

    $BASEPATH/src/$PLATFORM/install.sh

elif [ "$SUBCOMMAND" == "config" ]; then

    $BASEPATH/src/$PLATFORM/settings.sh
    $BASEPATH/src/$PLATFORM/bash.sh config
    $BASEPATH/src/$PLATFORM/zsh.sh config
    $BASEPATH/src/$PLATFORM/git.sh config
    $BASEPATH/src/$PLATFORM/gpg.sh config
    $BASEPATH/src/$PLATFORM/ssh.sh config

elif [ "$SUBCOMMAND" == "ssh" ]; then

    $BASEPATH/src/$PLATFORM/ssh.sh "$@"

elif [ "$SUBCOMMAND" == "gpg" ]; then

    $BASEPATH/src/$PLATFORM/gpg.sh "$@"

elif [ "$SUBCOMMAND" == "help" ]; then

    echo -e "Available subcommands:"
    echo -e "    install: Install programs you need"
    echo -e "    config : Configure programs you need"
    echo -e "    help   : List the available subcommands"

else

    $BASEPATH/woohoo help

fi
