#!/usr/bin/env bash

source src/helper.sh
source config/.env

detect_platform
ln -s -f ./woohoo /usr/local/bin/woohoo

SUBCOMMAND=$1
shift 1

if [ "$SUBCOMMAND" == "install" ]; then

    ./src/$PLATFORM/install.sh

elif [ "$SUBCOMMAND" == "config" ]; then

    ./src/$PLATFORM/bash.sh config
    ./src/$PLATFORM/git.sh config
    ./src/$PLATFORM/ssh.sh config

elif [ "$SUBCOMMAND" == "ssh" ]; then

    ./src/$PLATFORM/ssh.sh "$@"

elif [ "$SUBCOMMAND" == "gpg" ]; then

    ./src/$PLATFORM/gpg.sh "$@"

elif [ "$SUBCOMMAND" == "help" ]; then

    echo -e "Available subcommands:"
    echo -e "    install: Install programs you need"
    echo -e "    config : Configure programs you need"
    echo -e "    help   : List the available subcommands"

else

    ./woohoo help

fi
